### ISSUE TITLE
Oh my god!

### ISSUE THREAD

**Issue by parro-it** [egoist/is-trademarked#1]
No one of this are trademarked by who you can guess:

❯ is-trademarked ava
✖ ava is a trademark

❯ is-trademarked tape
✖ tape is a trademark

❯ is-trademarked gulp
✖ gulp is a trademark

❯ is-trademarked grunt
✖ grunt is a trademark

❯ is-trademarked npm
✖ npm is a trademark

**Comment by egoist** [comment]
But I can't wait to tell you a good news, `angular` is still available while `react` `vue` were already taken

**Comment by parro-it** [comment]
Then let's open a business together. We will register angular and then sue Google.
I start to write first email:

```
Google: We’re reaching out to you as we’d very much like to use our name “angular”
for an important package that we are going to release....
```
