### ISSUE TITLE
Add trademark owner to the results

### ISSUE THREAD

**Issue by parro-it** [egoist/is-trademarked#2]
The website provide other details, such as  Description, S/N, Goods & Services Code.
Are they available using the API too?

**Comment by egoist** [comment]
I think this can be useful, we can use `cheerio` or something to do that, PR welcome 😁

**Comment by parro-it** [comment]
:+1:

**Comment by egoist** [comment]
Seems this following data we can retrieve from `markerapi.com`:

```
Description
Service code
S/N number
```

No owner name.

**Comment by parro-it** [comment]
The description could still be useful to understand if the owner is in a competing business...
I'm not a lawyer but as I understood from all recent buzz, this could be an important information to have

**Comment by egoist** [comment]
I've updated the API and now it returns data in the following format when the word is a trademark:

``` js
[
  {
    wordmark: 'NAME',
    reg: Tue May 20 2008 00:00:00 GMT+0800 (CST),
    description: 'General feature magazines',
    sn: '77119087',
    serviceCode: 'GS0161'
  }
]
```

and it supports search term like `mac*`.

**Comment by parro-it** [comment]
That's great!
