### ISSUE TITLE
Options to check all NPM packages of an author

### ISSUE THREAD

**Issue by parro-it** [egoist/is-trademarked#3]
E.g.:

``` bash
is-trademarked --author=parro-it

✔ debug-menu is available
✖ termite is a trademark
✔ folderify is available

...

```

**Comment by egoist** [comment]
Good idea 😄 But I think it can be done by another module using this module as api.

**Comment by parro-it** [comment]
That's fair, I can start write it. What about `canibekiked` as name :smile: ?

**Comment by egoist** [comment]
@parro-it such a good name, very easy to remember.

**Comment by parro-it** [comment]
:+1: I will start to put something together this evening. [Repo placeholder created](https://github.com/parro-it/canibekiked)

**Comment by parro-it** [comment]
I published a first version of the tool here: https://github.com/parro-it/canibekiked. It would be beautiful if you could give it a shot and give me some feedback.

**Comment by egoist** [comment]
Wow, it's quite good! 

Only one suggestion, you can use https://github.com/substack/text-table to align the result 😀

**Comment by egoist** [comment]
![pic](https://ooo.0o0.ooo/2016/03/26/56f6a8ab771c7.png)

Besides, I think the first line might not be neccessary, since we already know it's trademarked by the context. 😂

**Comment by parro-it** [comment]
Thank you for your suggestions @egoist . I'll improve the message as you suggest.
