### ISSUE TITLE
Should hard coded token being remove ?

### ISSUE THREAD

**Issue by yang-wei** [egoist/is-trademarked#4]
I believe that the [token](https://github.com/egoist/is-trademarked/blob/master/index.js#L12) is used to authenticate when using the api. If it's hard coded then it will expire soon.

**Comment by egoist** [comment]
I will look into this, can you suggest a better way to get trademark data?

**Comment by egoist** [comment]
It's hardcoded in markerapi.com website, so I think it's fine to use it for now.

**Comment by yang-wei** [comment]
then it's fair =)
