### ISSUE TITLE
User supplied API token

### ISSUE THREAD

**Issue by brandonb927** [egoist/is-trademarked#5]
I noticed that the API key is hard-coded into the module and [The Changelog just tweeted](https://twitter.com/changelog/status/713215588177485825) about this which means there's a bunch of downloads and users coming this way momentarily/soon. Also, couple that with the pricing of `markerapi` an you've got yourself an unusable token pretty quickly!

My suggestion would be to allow a user-supplied API token, thoughts?

**Comment by egoist** [comment]
Sure,I think this is worthwhile and it's easy to get a token from http://www.markerapi.com with 1,000 searches a month for free.

So PR welcome. 😄 or I might update this myself.

**Comment by egoist** [comment]
Thanks for the advice, the new version `1.2.0` supports user supplied token, CLI will be updated soon 🎉
